# Generated by Django 3.2.22 on 2023-11-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cli', models.CharField(max_length=200)),
                ('telefono_cli', models.IntegerField(blank=True, null=True)),
                ('direccion_cli', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('cliente_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_farm', models.CharField(max_length=200)),
                ('direccion_farm', models.CharField(max_length=200)),
                ('telefono_farm', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('farmacia_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prov', models.CharField(max_length=200)),
                ('direccion_prov', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.CharField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')], max_length=1)),
                ('fecha_votacion', models.DateField(blank=True, null=True)),
                ('comenta_votacion', models.TextField()),
                ('voto_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.cliente')),
                ('voto_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.producto')),
            ],
        ),
        migrations.CreateModel(
            name='SuministroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sum', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('costo_ud', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_sub', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente_sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='prov_sum_prod',
            field=models.ManyToManyField(through='App_Farmacia.SuministroProducto', to='App_Farmacia.Proveedor'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('CA', 'Caixa'), ('BB', 'BBVA'), ('UN', 'UNICAJA'), ('IN', 'ING Direct')], max_length=2)),
                ('cuenta_bancaria', models.CharField(max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('cliente_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.cliente')),
                ('subscripcion_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.subscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ger', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fecha_inicio_gestion', models.DateField()),
                ('gerente_farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emp', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('salario', models.FloatField(db_column='salario_empleado', default=1020.4)),
                ('farm_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prod_comprado', models.IntegerField(blank=True, null=True)),
                ('precio_ud', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.compra')),
                ('producto_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DatosFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('horario', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('farmacia_datos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='empleado_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.empleado'),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto_compra',
            field=models.ManyToManyField(related_name='producto_compra', through='App_Farmacia.DetalleCompra', to='App_Farmacia.Producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='productos_favoritos',
            field=models.ManyToManyField(related_name='productos_favoritos', to='App_Farmacia.Producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='votacion_prod',
            field=models.ManyToManyField(related_name='votacion_prod', through='App_Farmacia.Votacion', to='App_Farmacia.Producto'),
        ),
    ]
