# Generated by Django 4.2.7 on 2023-12-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='puntuacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1),
        ),
    ]
