# Generated by Django 4.2.7 on 2023-12-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerente',
            name='fecha_inicio_gestion',
            field=models.DateField(null=True),
        ),
    ]
