# Generated by Django 4.2.7 on 2024-03-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='cliente_promo',
        ),
        migrations.AddField(
            model_name='promocion',
            name='cliente_promo',
            field=models.ManyToManyField(blank=True, null=True, to='App_Farmacia.cliente'),
        ),
    ]
