# Generated by Django 4.2.7 on 2023-12-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.FloatField(default=1024.0),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='salario_ger',
            field=models.FloatField(default=2100.0),
        ),
    ]
