# Generated by Django 4.2.7 on 2024-03-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0002_remove_promocion_cliente_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='cliente_promo',
            field=models.ManyToManyField(to='App_Farmacia.cliente'),
        ),
    ]
