# Generated by Django 4.2.7 on 2023-12-17 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0002_alter_gerente_fecha_inicio_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerente',
            name='gerente_farm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.farmacia'),
        ),
    ]
