# Generated by Django 4.2.7 on 2023-12-14 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0002_alter_votacion_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='fecha_votacion',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='puntuacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
