# Generated by Django 4.2.7 on 2023-12-14 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0003_alter_votacion_fecha_votacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='fecha_votacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
