# Generated by Django 4.2.7 on 2024-03-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0003_alter_promocion_cliente_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='cliente_promo',
            field=models.ManyToManyField(blank=True, to='App_Farmacia.cliente'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin_promo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
