# Generated by Django 4.2.8 on 2023-12-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0004_alter_votacion_fecha_votacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promo', models.CharField(max_length=100)),
                ('descripcion_promo', models.TextField()),
                ('valor_promo', models.IntegerField(default=0)),
                ('fecha_fin_promo', models.DateField()),
                ('cliente_promo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Farmacia.cliente')),
            ],
        ),
    ]
